folder: naics6-bees-counties
save-training: false
features:
  data: industries
  startyear: 2017
  endyear: 2021
  naics: [6]
  state: ME,NY
  common: Fips
  path: https://raw.githubusercontent.com/ModelEarth/community-timelines/main/training/naics{naics}/US/counties/{year}/US-{state}-training-naics{naics}-counties-{year}.csv
targets:
  data: bees
  path: https://raw.githubusercontent.com/ModelEarth/bee-data/main/targets/bees-targets-top-20-percent.csv
models: xgboost
